package org.erp.reflectrotechodoo.customer.entity;

import jakarta.persistence.*;
import lombok.*;
import lombok.experimental.SuperBuilder;
import org.erp.reflectrotechodoo.common.entity.BaseEntity;
import org.erp.reflectrotechodoo.customer.enums.CustomerType;
import org.erp.reflectrotechodoo.customer.enums.GstType;

import java.math.BigDecimal;

/**
 * Customer aggregate root.
 *
 * <p>Represents a buyer of RF Electrotech's PCB manufacturing services.
 * Linked to Quotations, Sales Orders, Invoices, and Payment records.
 *
 * <p>Inherits: id, uuid, status, deleted, version, createdAt, updatedAt,
 * createdBy, updatedBy from {@link BaseEntity}.
 *
 * <p>Indexing strategy:
 * <ul>
 *   <li>Unique: email, gstNumber, panNumber (where applicable)</li>
 *   <li>Composite search index: customerCode, companyName, city, state</li>
 * </ul>
 */
@Entity
@Table(
        name = "customers",
        indexes = {
                @Index(name = "idx_customer_code",         columnList = "customer_code", unique = true),
                @Index(name = "idx_customer_email",        columnList = "email",         unique = true),
                @Index(name = "idx_customer_gst",          columnList = "gst_number"),
                @Index(name = "idx_customer_pan",          columnList = "pan_number"),
                @Index(name = "idx_customer_company",      columnList = "company_name"),
                @Index(name = "idx_customer_deleted",      columnList = "deleted"),
                @Index(name = "idx_customer_type_status",  columnList = "customer_type, status")
        }
)
@Getter
@Setter
@NoArgsConstructor
@SuperBuilder
public class Customer extends BaseEntity {

    // ── Identity ──────────────────────────────────────────────────────────────

    /**
     * Human-readable unique customer code. Auto-generated by service layer.
     * Pattern: CUST-{YYYYMMDD}-{SEQ5} e.g. CUST-20240115-00001
     */
    @Column(name = "customer_code", nullable = false, unique = true, length = 25)
    private String customerCode;

    @Column(name = "company_name", nullable = false, length = 200)
    private String companyName;

    /** Legal / trading name used on invoices if different from company name. */
    @Column(name = "display_name", length = 200)
    private String displayName;

    @Enumerated(EnumType.STRING)
    @Column(name = "customer_type", nullable = false, length = 20)
    private CustomerType customerType;

    // ── Contact ───────────────────────────────────────────────────────────────

    @Column(name = "email", unique = true, length = 150)
    private String email;

    @Column(name = "phone", length = 20)
    private String phone;

    @Column(name = "alternate_phone", length = 20)
    private String alternatePhone;

    @Column(name = "website", length = 200)
    private String website;

    // ── Primary Address ───────────────────────────────────────────────────────

    @Column(name = "address_line1", length = 255)
    private String addressLine1;

    @Column(name = "address_line2", length = 255)
    private String addressLine2;

    @Column(name = "city", length = 100)
    private String city;

    @Column(name = "state", length = 100)
    private String state;

    @Column(name = "pincode", length = 10)
    private String pincode;

    @Column(name = "country", length = 100)
    @Builder.Default
    private String country = "India";

    // ── GST / Tax ─────────────────────────────────────────────────────────────

    /**
     * 15-digit Indian GST Identification Number.
     * Format: 2-digit state code + 10-digit PAN + 1-digit entity num + 1Z + 1 check.
     */
    @Column(name = "gst_number", length = 15)
    private String gstNumber;

    @Enumerated(EnumType.STRING)
    @Column(name = "gst_type", nullable = false, length = 20)
    @Builder.Default
    private GstType gstType = GstType.UNREGISTERED;

    /** 10-character alphanumeric PAN number. */
    @Column(name = "pan_number", length = 10)
    private String panNumber;

    // ── Commercial Terms ──────────────────────────────────────────────────────

    /** Credit limit in INR (0 = COD/no credit). */
    @Column(name = "credit_limit", precision = 15, scale = 2)
    @Builder.Default
    private BigDecimal creditLimit = BigDecimal.ZERO;

    /** Payment terms in days (e.g. 30, 45, 60). */
    @Column(name = "payment_terms_days")
    @Builder.Default
    private Integer paymentTermsDays = 0;

    // ── CRM ───────────────────────────────────────────────────────────────────

    /** Internal notes / remarks visible to the sales team only. */
    @Column(name = "notes", columnDefinition = "TEXT")
    private String notes;

    /** Primary contact person name at the customer organisation. */
    @Column(name = "contact_person", length = 150)
    private String contactPerson;

    /** Designation of the primary contact person. */
    @Column(name = "contact_designation", length = 100)
    private String contactDesignation;
}
