package org.erp.reflectrotechodoo.customer.mapper;

import org.erp.reflectrotechodoo.customer.dto.request.CustomerRequest;
import org.erp.reflectrotechodoo.customer.dto.response.CustomerResponse;
import org.erp.reflectrotechodoo.customer.entity.Customer;
import org.mapstruct.*;

/**
 * MapStruct mapper for the Customer aggregate.
 *
 * <p>Configuration decisions:
 * <ul>
 *   <li>{@code componentModel = "spring"} — registered as a Spring bean (set globally via compiler arg).</li>
 *   <li>{@code nullValuePropertyMappingStrategy = IGNORE} on {@code update()} — ensures PATCH semantics:
 *       only non-null request fields overwrite the existing entity state.</li>
 *   <li>{@code unmappedTargetPolicy = ERROR} — compile-time failure if a target field is accidentally
 *       left unmapped, preventing silent data loss.</li>
 * </ul>
 *
 * <p><strong>Note:</strong> {@code id}, {@code uuid}, {@code customerCode}, {@code createdAt},
 * {@code updatedAt}, {@code createdBy}, {@code updatedBy}, {@code version} are managed by
 * JPA/Hibernate and the audit framework — they must NEVER be set from request DTO.
 */
@Mapper(
        unmappedTargetPolicy = ReportingPolicy.ERROR,
        nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE
)
public interface CustomerMapper {

    /**
     * Maps a {@link CustomerRequest} to a new {@link Customer} entity for CREATE.
     * Fields managed by infrastructure (id, uuid, version, audit fields) are
     * ignored — JPA populates them automatically.
     */
    @Mapping(target = "id",                  ignore = true)
    @Mapping(target = "uuid",                ignore = true)
    @Mapping(target = "customerCode",        ignore = true) // generated by service
    @Mapping(target = "version",             ignore = true)
    @Mapping(target = "deleted",             ignore = true)
    @Mapping(target = "status",              ignore = true)
    @Mapping(target = "createdAt",           ignore = true)
    @Mapping(target = "updatedAt",           ignore = true)
    @Mapping(target = "createdBy",           ignore = true)
    @Mapping(target = "updatedBy",           ignore = true)
    Customer toEntity(CustomerRequest request);

    /**
     * Maps a {@link Customer} entity to a {@link CustomerResponse} DTO for API output.
     */
    CustomerResponse toResponse(Customer customer);

    /**
     * Applies non-null fields from {@link CustomerRequest} onto an existing
     * {@link Customer} entity for UPDATE/PATCH operations.
     *
     * <p>The {@code @MappingTarget} annotation tells MapStruct to mutate the
     * existing entity instead of creating a new instance.
     */
    @Mapping(target = "id",           ignore = true)
    @Mapping(target = "uuid",         ignore = true)
    @Mapping(target = "customerCode", ignore = true)
    @Mapping(target = "version",      ignore = true)
    @Mapping(target = "deleted",      ignore = true)
    @Mapping(target = "status",       ignore = true)
    @Mapping(target = "createdAt",    ignore = true)
    @Mapping(target = "updatedAt",    ignore = true)
    @Mapping(target = "createdBy",    ignore = true)
    @Mapping(target = "updatedBy",    ignore = true)
    void updateEntityFromRequest(CustomerRequest request, @MappingTarget Customer customer);
}
